// Code generated by protofix; DO NOT EDIT.
// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package testspec provides test FIX.0.1 protocol format.
package testspec

import (
	f0 "github.com/protofix/protofix/codecfix"
	"github.com/protofix/protofix/marshfix"
)

var (
	TESTSPECLogonMarshaler   = marshfix.Marshal{Tag: "TESTSPEC", Format: TESTSPECLogon}
	TESTSPECLogonUnmarshaler = marshfix.Unmarshal{Tag: "TESTSPEC", Format: TESTSPECLogon}
)

// TESTSPECLogon is a test FIX.0.1 format of the Logon message which maps the codecs into individual fields.
var TESTSPECLogon = f0.Format{
	Fields: map[int]f0.Codec{
		BeginString8:           f0.Fld{Req, f0.ASCII, f0.StringDefault("FIX.0.1"), f0.Con{7}},
		MsgType35:              f0.Fld{Req, f0.ASCII, f0.String("0" /* HEARTBEAT */, "5" /* LOGOUT */, "A" /* LOGON */), f0.Var{1, 2}},
		SenderCompID49:         f0.Fld{Req, f0.ASCII, f0.String(), f0.Var{1, 65536}},
		TargetCompID56:         f0.Fld{Req, f0.ASCII, f0.String(), f0.Var{1, 65536}},
		MsgSeqNum34:            f0.Fld{Opt, f0.ASCII, f0.SeqNum(), f0.Var{1, 19}},
		PossDupFlag43:          f0.Fld{Opt, f0.ASCII, f0.BoolDefault(false /* NO */, true /* YES */), f0.Con{1}},
		PossResend97:           f0.Fld{Opt, f0.ASCII, f0.BoolDefault(false /* NO */, true /* YES */), f0.Con{1}},
		SendingTime52:          f0.Fld{Req, f0.ASCII, f0.UTCTimestampMillisecondTime(), f0.Var{1, 27}},
		OrigSendingTime122:     f0.Fld{Opt, f0.ASCII, f0.UTCTimestampMillisecondTime(), f0.Var{1, 27}},
		AgreementDesc913:       f0.Fld{Opt, f0.ASCII, f0.String(), f0.Var{1, 65536}},
		YieldType235:           f0.Fld{Opt, f0.ASCII, f0.String("AFTERTAX" /* AFTERTAXYIELD */), f0.Var{1, 65536}},
		UnderlyingStipType888:  f0.Fld{Opt, f0.ASCII, f0.String(), f0.Var{1, 65536}},
		HopCompID628:           f0.Fld{Opt, f0.ASCII, f0.String(), f0.Var{1, 65536}},
		EncryptMethod98:        f0.Fld{Req, f0.ASCII, f0.IntDefault(0 /* NONEOTHER */), f0.Con{1}},
		HeartBtInt108:          f0.Fld{Req, f0.ASCII, f0.SecondsDuration(1000000000, 2000000000, 3000000000, 4000000000, 5000000000, 6000000000, 7000000000, 8000000000, 9000000000, 10000000000, 11000000000, 12000000000, 13000000000, 14000000000, 15000000000, 16000000000, 17000000000, 18000000000, 19000000000, 20000000000, 21000000000, 22000000000, 23000000000, 24000000000, 25000000000, 26000000000, 27000000000, 28000000000, 29000000000, 30000000000, 31000000000, 32000000000, 33000000000, 34000000000, 35000000000, 36000000000, 37000000000, 38000000000, 39000000000, 40000000000, 41000000000, 42000000000, 43000000000, 44000000000, 45000000000, 46000000000, 47000000000, 48000000000, 49000000000, 50000000000, 51000000000, 52000000000, 53000000000, 54000000000, 55000000000, 56000000000, 57000000000, 58000000000, 59000000000, 60000000000), f0.Var{1, 18}},
		ResetSeqNumFlag141:     f0.Fld{Opt, f0.ASCII, f0.BoolDefault(false /* NO */, true /* YES */), f0.Con{1}},
		Password554:            f0.Fld{Req, f0.ASCII, f0.String(), f0.Var{1, 65536}},
		NewPassword925:         f0.Fld{Opt, f0.ASCII, f0.String(), f0.Var{1, 65536}},
		SessionStatus1409:      f0.Fld{Opt, f0.ASCII, f0.IntDefault(0, 3), f0.Var{1, 19}},
		CancelOnDisconnect6867: f0.Fld{Opt, f0.ASCII, f0.String("A"), f0.Var{1, 65536}},
		LanguageID6936:         f0.Fld{Opt, f0.ASCII, f0.String("R" /* RUSSIAN */, "E" /* ENGLISH */), f0.Var{1, 65536}},
		PosType703:             f0.Fld{Opt, f0.ASCII, f0.String("ALC" /* ALLOCATION_TRADE_QTY */, "AS" /* OPTION_ASSIGNMENT */), f0.Var{1, 65536}},
		NestedPartyID524:       f0.Fld{Opt, f0.ASCII, f0.String(), f0.Var{1, 65536}},
		NestedPartySubID545:    f0.Fld{Opt, f0.ASCII, f0.String(), f0.Var{1, 65536}},
	},
	BodyLength9: f0.BodyLengthFld{f0.ASCII, f0.BodyLength(), f0.Var{1, 18}},
	CheckSum10:  f0.CheckSumFld{f0.ASCII, f0.CheckSum(), f0.Con{3}},
	Unknown0:    f0.UnknownFld{f0.ASCII, f0.Unknown(), f0.Var{1, 65536}},
	Sort: []int{
		BeginString8,           // STRING
		BodyLength9,            // LENGTH
		MsgType35,              // STRING
		SenderCompID49,         // STRING
		TargetCompID56,         // STRING
		MsgSeqNum34,            // SEQNUM
		PossDupFlag43,          // BOOLEAN
		PossResend97,           // BOOLEAN
		SendingTime52,          // UTCTIMESTAMP
		OrigSendingTime122,     // UTCTIMESTAMP
		AgreementDesc913,       // STRING
		YieldType235,           // STRING
		UnderlyingStipType888,  // STRING
		HopCompID628,           // STRING
		EncryptMethod98,        // INT
		HeartBtInt108,          // INT
		ResetSeqNumFlag141,     // BOOLEAN
		Password554,            // STRING
		NewPassword925,         // STRING
		SessionStatus1409,      // INT
		CancelOnDisconnect6867, // STRING
		LanguageID6936,         // STRING
		PosType703,             // STRING
		NestedPartyID524,       // STRING
		NestedPartySubID545,    // STRING
		CheckSum10,             // STRING
	},
}
